name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
 
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  equatable: ^2.0.5
  multiple_result: ^5.1.0
  cloud_firestore: ^5.4.4

  flutter:
    sdk: flutter
 
dev_dependencies:
  flutter_test:
    sdk: flutter
 
